spring:
    application:
        name: medportalserver

    datasource:
        url: jdbc:postgresql://localhost:5433/postgres
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}

    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
        show-sql: true

    security:
        user:
            name: ${ADMIN_USER}
            password: ${ADMIN_PASS}
            roles: [ "ADMIN" ]

    mail:
        host: smtp.gmail.com
        port: 587
        username: ${MAIL_USER}
        password: ${MAIL_PASS}
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
                    timeout: 5000
                    connectiontimeout: 5000
                    writetimeout: 5000

registration:
    secret: ${REGISTRATION_SECRET}
