package com.server.medportalserver;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.scheduling.annotation.EnableAsync;

// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@EnableAsync
@SpringBootApplication
public class MedportalserverApplication {

	public static void main(String[] args) {
		SpringApplication.run(MedportalserverApplication.class, args);
	}

}
